// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: passenger.sql

package db

import (
	"context"
	"database/sql"
)

const createPassenger = `-- name: CreatePassenger :one
INSERT INTO passenger (
  phone,
  name
) VALUES (
  $1, $2
)
RETURNING id, phone, name, date_of_birth, avatar_url, created_at
`

type CreatePassengerParams struct {
	Phone string `json:"phone"`
	Name  string `json:"name"`
}

func (q *Queries) CreatePassenger(ctx context.Context, arg CreatePassengerParams) (Passenger, error) {
	row := q.db.QueryRowContext(ctx, createPassenger, arg.Phone, arg.Name)
	var i Passenger
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.DateOfBirth,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deletePassenger = `-- name: DeletePassenger :exec
DELETE FROM passenger
WHERE phone = $1
`

func (q *Queries) DeletePassenger(ctx context.Context, phone string) error {
	_, err := q.db.ExecContext(ctx, deletePassenger, phone)
	return err
}

const getPassenger = `-- name: GetPassenger :one
SELECT id, phone, name, date_of_birth, avatar_url, created_at FROM passenger
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPassenger(ctx context.Context, id int64) (Passenger, error) {
	row := q.db.QueryRowContext(ctx, getPassenger, id)
	var i Passenger
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.DateOfBirth,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getPassengerByPhone = `-- name: GetPassengerByPhone :one
SELECT id, phone, name, date_of_birth, avatar_url, created_at FROM passenger
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetPassengerByPhone(ctx context.Context, phone string) (Passenger, error) {
	row := q.db.QueryRowContext(ctx, getPassengerByPhone, phone)
	var i Passenger
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.DateOfBirth,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getPassengerForUpdate = `-- name: GetPassengerForUpdate :one
SELECT id, phone, name, date_of_birth, avatar_url, created_at FROM passenger
WHERE id = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetPassengerForUpdate(ctx context.Context, id int64) (Passenger, error) {
	row := q.db.QueryRowContext(ctx, getPassengerForUpdate, id)
	var i Passenger
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.DateOfBirth,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listPassengers = `-- name: ListPassengers :many
SELECT id, phone, name, date_of_birth, avatar_url, created_at FROM passenger
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListPassengersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPassengers(ctx context.Context, arg ListPassengersParams) ([]Passenger, error) {
	rows, err := q.db.QueryContext(ctx, listPassengers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Passenger
	for rows.Next() {
		var i Passenger
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.Name,
			&i.DateOfBirth,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassenger = `-- name: UpdatePassenger :one
UPDATE passenger
SET name = $2,
  date_of_birth = $3
WHERE phone = $1
RETURNING id, phone, name, date_of_birth, avatar_url, created_at
`

type UpdatePassengerParams struct {
	Phone       string       `json:"phone"`
	Name        string       `json:"name"`
	DateOfBirth sql.NullTime `json:"date_of_birth"`
}

func (q *Queries) UpdatePassenger(ctx context.Context, arg UpdatePassengerParams) (Passenger, error) {
	row := q.db.QueryRowContext(ctx, updatePassenger, arg.Phone, arg.Name, arg.DateOfBirth)
	var i Passenger
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.DateOfBirth,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}
